//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEcom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Category
    {
        public int CategoryId { get; set; }
        [Required]
        public string CategoryName { get; set; }
        [Required]
        public string CategoryDescription { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public Category()
        {
            this.Products = new HashSet<Product>();
        }

        public List<SelectListItem> Listitems { get; set; }
        [DefaultValue(true)]
        [Display(Name = "Active/Deactive")]
        public Nullable<bool> CategoryActive { get; set; }
        public string ISActive
        {
            get
            {
                return (bool)this.CategoryActive ? "Active" : "Deactive";
            }
        }

        public HashSet<Product> Products { get; set; }
    }
}
