//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEcom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EcomerceEntities1 : DbContext
    {
        public EcomerceEntities1()
            : base("name=EcomerceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<USP_Admin_GetProductDetails_Result> USP_Admin_GetProductDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Admin_GetProductDetails_Result>("USP_Admin_GetProductDetails");
        }
    
        public virtual ObjectResult<USP_Admin_GetProductDetailsByID_Result> USP_Admin_GetProductDetailsByID(string productID)
        {
            var productIDParameter = productID != null ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Admin_GetProductDetailsByID_Result>("USP_Admin_GetProductDetailsByID", productIDParameter);
        }
    }
}
