//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEcom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {
        //public int ProductId { get; set; }
        //public string ProductName { get; set; }
        //public Nullable<int> Quantity { get; set; }
        //public Nullable<double> Price { get; set; }
        //public Nullable<int> ImageId { get; set; }
        //public Nullable<int> CategoryId { get; set; }
        //public Nullable<System.DateTime> CreationDate { get; set; }
        //public Nullable<System.DateTime> UpdationDate { get; set; }

        public Product()
        {
            this._CategoryListNew = new List<SelectListItem>();
            this._ImageListNew = new List<SelectListItem>();
        }
        public List<SelectListItem> _CategoryListNew { get; set; }
        public List<SelectListItem> _ImageListNew { get; set; }

        public int ProductId { get; set; }
        [Required]
        [DisplayName("Product Name")]
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        [DisplayName("Image Name")]
        [Required]
        public Nullable<int> ImageId { get; set; }
        [DisplayName("Category Name")]
        [Required]
        public Nullable<int> CategoryId { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public string Imagefilename { get; set; }


        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }


        public List<Category> ListOfCategory { get; set; }
        public List<Image> ListOfImage { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> _CategoryList { get; set; }
    }
}
